### ISSUE TITLE
Configure Schema ID/Key

### ISSUE THREAD

**Issue by ericingram** [insoftpub/storefront#1]
What's the right way to configure Schema ID/Key?

**Comment by vmajsuk** [comment]
Hi Eric!
Schema ID/Key are configured in the  /servers/api/config.js, so to configure it, edit auth.schemaIO.clientId and auth.schemaIO.clientSecret properties.

**Comment by ericingram** [comment]
@vmajsuk Thanks!

I'm wondering about dev vs production, how would you recommend setting these configs for different environments?

**Comment by vmajsuk** [comment]
@ericingram for the most part, server configs store some services' ids and keys, so they are similar for dev and production. The only thing i can recall is you can change `CACHE_MAX_AGE` in `/servers/static/config.js`

**Comment by ericingram** [comment]
I think it would be ideal to support ENV variables for these configurations, as an override to the hard coded configs at least.

**Comment by isdminch** [comment]
Agreed, will be easier and secure to maintain boilerplate code base with ENV variables at PM2 ecosystem file instead. Else we may accidentally commit private data of the demo store to public repo. I will create TODO.
