### ISSUE TITLE
npm start (api?)

### ISSUE THREAD

**Issue by ericingram** [insoftpub/storefront#3]
When running `npm start`, it goes fine but then fails because the API server is not run by default on port 4001. I can get it going by starting a 2nd console with `npm run api`, and then back to `npm start`. Maybe an oversight?

**Comment by vmajsuk** [comment]
@ericingram yes, you need to execute `npm start` and `npm run api` in different consoles.

The thing is we have two servers: static and api, and both of them need to be run for the application to work. So you basically run static server by executing `npm start` in one console, and run api server by executing `npm run api` in the different one.

Of course, it would be easier to run both servers with one command, but we didn't find a way to do it.
Suggestions are welcome.

**Comment by ericingram** [comment]
That makes sense. We also developed a separate API (https://github.com/schemaio/schema-node-api) and of course it has to be run separately. I'll make a PR to explain this in the README unless you beat me to it :)
