### ISSUE TITLE
Image Undefined

### ISSUE THREAD

**Issue by stevecawdery** [insoftpub/storefront#4]
Hi,

The image i put on SchemaIO for a Test Product doesn't load when I pull up my version of your Storefront. I get in console:

Warning: Failed prop type: The prop `src` is marked as required in `Image`, but its value is `undefined`.

I'm not sure where to look in order to solve this. Any input is appreciated.

Thanks.

**Comment by vmajsuk** [comment]
@stevecawdery we've fixed this in the latest commit. Check out the changes:
https://github.com/insoftpub/storefront/commit/956c939f38ec13d70d5ce0c1767a6f0cfb42d3e1#diff-f32a2548ba54b562e8a63dd47ff2e5d0
